### ISSUE TITLE
CPTP and WPML

### ISSUE THREAD

**Issue by Colir** [torounit/custom-post-type-permalinks#10]
Hi, Can we imagine to have this plugin work with WPML ?

i've set the permalink to have URL like this

www.website.com/cpt/taxonomy/term
with wpml i've this url wich work fine
www.website.com/fr/cpt/taxonomy/term

But when i use the language switcher from wpml
the url is www.website.com/cpt/fr/taxonomy/term

and so this didn't work

**Comment by romainhe** [comment]
Hi, does anyone have a solution for this issue..?

**Comment by szepeviktor** [comment]
@torounit Could you help us?

**Comment by guiguimou** [comment]
Yes, that'll be the best improvment for this plugin ! We need to use permalinks simply with the parmater "lang=en" at the good place, and not a the middle of the permalink...

Please help us!

**Comment by keichan34** [comment]
@Colir @szepeviktor @romainhe @guiguimou Can you please try the patch in #45 and see if it works for you?

**Comment by szepeviktor** [comment]
I am very sorry. I've forgot which site it was.
