### ISSUE TITLE
Does not work in multisite with subfolders

### ISSUE THREAD

**Issue by gabbsmo** [torounit/custom-post-type-permalinks#11]
1. Set permalink structure in network admin
2. Set structure to default in site dashboard

This configuration is a perquisite for removing the blog slug from a multisite installation with subfolders. CPTP does not support the configuration and will fallback to using the query string. Thus not inheriting the structure from network admin.

If no fix can be provided a note should be added in the plugin description.

**Comment by jimmymorrisuk** [comment]
Any news on this?
