### ISSUE TITLE
Page 404 error if subcategory

### ISSUE THREAD

**Issue by TheZoker** [torounit/custom-post-type-permalinks#30]
Hi there,

I got a 404 error, if I try to use /%portfolio_categories%/%postname% and there is a subcategory.

So like: site.com/phones/iphone/new-iphone-6

Phone is category, iphone is subcategory and new-iphone-6 is post item.

Can you please fix thisß

Thank you

**Comment by Infolu** [comment]
Same problem here

**Comment by bilalmalkoc** [comment]
Year 2020. Same problem.
