### ISSUE TITLE
pt_BR translation

### ISSUE THREAD

**Issue by bruno-barros** [torounit/custom-post-type-permalinks#38]
If you like [here](https://github.com/bruno-barros/wp-plugins-translations/tree/master/custom-post-type-permalinks) is a Potuguese translation.

**Comment by torounit** [comment]
Thanks!!!

Please give me Pull Request!. 
That way , your account will be displayed on [Contributors](https://github.com/torounit/custom-post-type-permalinks/graphs/contributors).
