### ISSUE TITLE
post_type_link filter function breaks multi-language permalinks

### ISSUE THREAD

**Issue by aurovrata** [torounit/custom-post-type-permalinks#48]
I found 2 bugs which breaks the multi-language permalinks created by the Polylang plugin.  The detailed bugs are listed in this Wordpress [support thread](https://wordpress.org/support/topic/breaks-polylang-translation-links?replies=1).

**Comment by torounit** [comment]
https://wordpress.org/support/topic/breaks-polylang-translation-links?replies=5#post-7726219
