### ISSUE TITLE
Add WooCommerce support

### ISSUE THREAD

**Issue by kuiperr005** [torounit/custom-post-type-permalinks#50]
This plugin runs into a couple of permalink structure issues if used in combination with WooCommerce.

For example, there are double slashes inside the permalink structure when you select a custom shop base option for products and product categories, http://ROOTURL//shop/%product_cat% 

Would be great if this could be fixed!

**Comment by torounit** [comment]
Plase Try https://wordpress.org/plugins/woocommerce-breadcrumb-permalinks/ !
