### ISSUE TITLE
add_rewrite_rules triggered after save_post

### ISSUE THREAD

**Issue by torarnv** [torounit/custom-post-type-permalinks#53]
The priority of 100 when adding the `add_rewrite_rules` hook for `wp_loaded` means that `add_permastruct` is called after the `save_post` action. This means `get_post_permalink` will not give the right permalink in `save_post`. 

With a priority of 10 it works fine. Why is the priority 100? Would another hook than `wp_loaded` be more appropriate?

**Comment by torarnv** [comment]
This seems due to piklist processing their front end forms in `add_action('wp_loaded', array('piklist_form', 'wp_loaded'), 100);`

**Comment by torarnv** [comment]
Not sure if `piklist` is doing the right thing saving forms in `wp_loaded`, and if they are, how to ensure `custom-post-type-permalinks` runs first, besides bumping the priority in `piklist`. Thoughts?

**Comment by torounit** [comment]
In the old days, since the conflicts with other plug-ins, I think I was set to 100.
However, I do not think there is much of a reason. 

Please pull request!

**Comment by torounit** [comment]
https://github.com/torounit/custom-post-type-permalinks/commit/5d5a7bc3589f7af3701a9182e8096b696e93acc8

marge your issue
