### ISSUE TITLE
Term query is not cached causing lots of queries to be made

### ISSUE THREAD

**Issue by saadibrahim** [torounit/custom-post-type-permalinks#55]
Hi

https://github.com/torounit/custom-post-type-permalinks/blob/master/CPTP/Module/Permalink.php#L199

wp_get_post_terms isnt cached by default causing a lot of queries to be made, every time theres a get_permalink or the_permalink in the code it causes a lot of queries and slow down the site.. especially in a loop.

I changed it to get_the_terms (removing the third argument array( 'orderby' => 'term_id' )) which improved the performance quite a bit but I dont know what are the side effects of it.

Thanks!

**Comment by torounit** [comment]
Oh Thanks Report! 

Please send Pull Request!!
