### ISSUE TITLE
Problem with nested/hierarchical custom taxonomies

### ISSUE THREAD

**Issue by kkerley** [torounit/custom-post-type-permalinks#60]
I've been struggling to get nested custom taxonomy terms on a custom post type. I'm doing a custom post type called 'product' and the taxonomy is 'product-type'. For my testing, I have created the parent taxonomy term 'album' and it has three children: 'EP', 'LP', and 'Single'. 

I came across this plugin not long ago and it's great, except for one incredibly frustrating aspect:

This is my custom permalink structure: /%product_type%/%postname%/

No matter what I put in the rewrite rules for the custom taxonomy's slug, or for the has_archive value on the custom post type, if I check "Use custom permalink of custom taxonomy archive", then the following behavior happens:

/product/album/ WORKS
/product/album/lp WORKS
/product/album/lp/nevermind DOES NOT WORK

If I uncheck that box and set has_archive => 'product' or has_archive => true and slug rewrite => 'product', the following behavior happens:

/product/album/ WORKS
/product/album/lp DOES NOT WORK
/product/album/lp/nevermind WORKS

I'm completely baffled. I've tried changing the slug and has_archive values both to be product/%product_type% to no avail. Am I missing something very obvious? 

Here are my functions for registering the custom post type and taxonomy:

    function create_product_post_type() {

		$labels = array(
			'name'                  => 'Products',
			'singular_name'         => 'Product',
			'menu_name'             => 'Products',
			'name_admin_bar'        => 'Product',
			'archives'              => 'Product Archives',
			'parent_item_colon'     => 'Parent Product:',
			'all_items'             => 'All Products',
			'add_new_item'          => 'Add New Product',
			'add_new'               => 'Add New',
			'new_item'              => 'New Product',
			'edit_item'             => 'Edit Product',
			'update_item'           => 'Update Product',
			'view_item'             => 'View Product',
			'search_items'          => 'Search Product',
			'not_found'             => 'Not found',
			'not_found_in_trash'    => 'Not found in Trash',
			'featured_image'        => 'Featured Image',
			'set_featured_image'    => 'Set featured image',
			'remove_featured_image' => 'Remove featured image',
			'use_featured_image'    => 'Use as featured image',
			'insert_into_item'      => 'Insert into Product',
			'uploaded_to_this_item' => 'Uploaded to this Product',
			'items_list'            => 'Products list',
			'items_list_navigation' => 'Products list navigation',
			'filter_items_list'     => 'Filter Products list',
		);
		$args = array(
			'label'                 => 'Product',
			'description'           => 'Post Type Description',
			'labels'                => $labels,
			'supports'              => array( 'title', 'editor', 'thumbnail', ),
			'taxonomies'            => array( 'product-type' ),
			'hierarchical'          => false,
			'public'                => true,
			'show_ui'               => true,
			'show_in_menu'          => true,
			'menu_position'         => 5,
			'menu_icon'             => 'dashicons-editor-removeformatting',
			'show_in_admin_bar'     => true,
			'show_in_nav_menus'     => true,
			'can_export'            => true,
			'has_archive'           => 'product',
			'exclude_from_search'   => false,
			'publicly_queryable'    => true,
			'capability_type'       => 'page',
		);
		register_post_type( 'product', $args );

	}
	add_action( 'init', 'create_product_post_type', 0 );

	function create_post_type_taxonomy() {

		$labels = array(
			'name'                       => 'Product Types',
			'singular_name'              => 'Product Type',
			'menu_name'                  => 'Product Type',
			'all_items'                  => 'All Product Types',
			'parent_item'                => 'Parent Product Type',
			'parent_item_colon'          => 'Parent Product Type:',
			'new_item_name'              => 'New Product Type Name',
			'add_new_item'               => 'Add New Product Type',
			'edit_item'                  => 'Edit Product Type',
			'update_item'                => 'Update Product Type',
			'view_item'                  => 'View Product Type',
			'separate_items_with_commas' => 'Separate Product Types with commas',
			'add_or_remove_items'        => 'Add or remove Product Types',
			'choose_from_most_used'      => 'Choose from the most used',
			'popular_items'              => 'Popular Product Types',
			'search_items'               => 'Search Product Types',
			'not_found'                  => 'Not Found',
			'no_terms'                   => 'No items',
			'items_list'                 => 'Product Types list',
			'items_list_navigation'      => 'Product Types list navigation',
		);
		$rewrite = array(
			'slug'                       => 'product',
			'with_front'                 => false,
			'hierarchical'               => true,
		);
		$args = array(
			'labels'                     => $labels,
			'hierarchical'               => true,
			'public'                     => true,
			'show_ui'                    => true,
			'show_admin_column'          => true,
			'show_in_nav_menus'          => true,
			'show_tagcloud'              => false,
			'rewrite'                    => $rewrite,
		);
		register_taxonomy( 'product_type', array( 'product' ), $args );

	}
	add_action( 'init', 'create_post_type_taxonomy', 0 );

It's so frustrating that I can get 2/3 of the way there. Either the nested custom taxonomy works and the actual product does not, or only the top-level custom taxonomy term works as well as the product.

**Comment by torounit** [comment]
@kkerley 
Sorry, Not support now if the same slug between post types and taxonomies.

**Comment by kkerley** [comment]
Aha! I changed the slug to 'products' for the taxonomy and now it works!

/products/album/ WORKS
/products/album/lp WORKS
/product/album/lp/nevermind WORKS

Thank you for clarifying that!
