### ISSUE TITLE
How to remove l'/' from url 

### ISSUE THREAD

**Issue by rvpatel** [torounit/custom-post-type-permalinks#64]
I have added .html in custom post type permalink but how to remove '/' aftre .html.

Like : http://sadasdas.com/asdads.html/
Want : http://sadasdas.com/asdads.html

**Comment by torounit** [comment]
Remove '/' in default permalink setting.

**Comment by rvpatel** [comment]
Thanks this on fix after select custom permalink and remove '/' from this.

**Comment by welcomecode** [comment]
Actually I using wp-types plugin for creating custom post-type, maybe it not working for types plugin.

**Comment by welcomecode** [comment]
Thanks
I just follow above tricks and it working properly.
