### ISSUE TITLE
Media attachment: howto

### ISSUE THREAD

**Issue by gereby** [torounit/custom-post-type-permalinks#69]
Would it be possible to add the attachment Post type to the list of editable permalinks?

**Comment by torounit** [comment]
not support editable permalink for attachment.

**Comment by gereby** [comment]
is there a technical reason for that?

**Comment by torounit** [comment]
@gereby 

This plugin is for custom post type. That function should be another plugin.

I would like to keep this plugin as simple as possible.

**Comment by gereby** [comment]
i can understand. unfortunatelly, there is no other plugin solving this –
