### ISSUE TITLE
Deprecated _usort_terms_by_ID

### ISSUE THREAD

**Issue by encodia** [torounit/custom-post-type-permalinks#73]
Hi there,

we did upgrade to 3.0.0 and we can notice the deprecated message on _usort_terms_by_ID

Line 130 Permalink.php
usort( $categories, '_usort_terms_by_ID' ); // order by ID

Thanks

**Comment by torounit** [comment]
@encodia Thanks Report. fixed issue!

ref. https://github.com/woocommerce/woocommerce/issues/12525
