### ISSUE TITLE
アップデートを行ったら月別、年別アーカイブのURLが変わってしまいました

### ISSUE THREAD

**Issue by shimbo-top** [torounit/custom-post-type-permalinks#74]
先日WPとプラグインのバージョンをアップデートしました

そうしたところ、今まで使用していたカスタム投稿の月別、年別アーカイブのURLが変わってしまいました。
元のURLで表示する方法は有りますでしょうか？

アップデートの前後バージョンと設定は下記のようになっております

◆バージョン
WordPress 3.9.1→4.7.2
Custom Post Type Permalinks  0.9.5.6→3.0.0

◆パーマリンク設定
/%year%%monthnum%%day%/%post_id%

◆これまでのURL
/topics/date/2016/
/topics/date/2016/12/

※カスタム投稿タイプはtopics
※アップデート後に「date/」付きのページでは404エラーになります
　 「date/」抜きのURLでは正常に表示できます

◆URL取得方法
wp_get_archives('post_type=topics&type=yearly&show_count=0&format=custom&echo=0')

wp_get_archives('post_type=topics&type=monthly&show_post_count=0&use_desc_for_title=0&echo=0');

※wp_get_archivesで取得するURLは「date/」付きですが、画面が404エラーになってしまいます
「date/」なしでアクセスすると正常に表示できる状況です

◆補足
パーマリンンク設定を「/%post_id%」のみにすれば今まで通りのアーカイブページURLになるのですが
記事のURLが変わってしまうので設定変更はしたくない、、という状況です

**Comment by torounit** [comment]
ver 1.0.0 より、WordPress の date アーカイブが url に `date` を挿入する場合で、かつ、その投稿タイプのパーマリンク設定に、`%post_id&` が入っているケースでのみ、date を挿入するようになりました。

開発版に、`CPTP_date_front` というフィルターを追加しました。

```php
add_filter( 'CPTP_date_front', 'my_cptp_date_front' );
function my_cptp_date_front(){
	return '/date';
}
```

のようなコードを追加することで、いかなる場合であっても `date`付きのパーマリンクに設定できます。

**Comment by shimbo-top** [comment]
ありがとうございます。
調整いただいたフィルターにて元の通りに動くようになりました。
